[tool.poetry]
name = "plsexplain"
version = "0.1.0"
description = "Create an explainable AI dashboard for your machine learning model."
authors = ["Willem Meints <willem.meints@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
plsexplain = "plsexplain.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
